env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
globals:
  JSX: readonly
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - jsx-a11y
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
root: true
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/consistent-type-imports': warn
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/prefer-as-const': warn
  '@typescript-eslint/no-var-requires': off
  no-alert: error
  no-dupe-keys: error
  no-duplicate-imports: off
  no-unused-private-class-members: error
  prettier/prettier:
    - warn
    - endOfLine: auto
    - properties:
        usePrettierrc: true
  react-hooks/rules-of-hooks: error
  react/react-in-jsx-scope: off
  camelcase: error
  quotes:
    - error
    - single
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
  react:
    version: detect
