name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  deploy:
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: snaplet/vercel-action@v2
        id: vercel-deploy
      - name: Notify update in PR
        uses: thollander/actions-comment-pull-request@v1
        if: success() && github.event.action == 'opened'
        with:
          message: |
            New beta version for this Pull Request has been released
            Service URL: ${{ steps.vercel-deploy.outputs.deployment-url.description }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  delete:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v2
        with:
          delete: true