name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Beta
        id: deploy
        run: echo "url=$(vercel --token=${{ env.VERCEL_ACCESS_TOKEN }})" >> $GITHUB_OUTPUT
      - name: Notify update in PR
        uses: thollander/actions-comment-pull-request@v1
        if: success()
        with:
          message: |
            New beta version for this Pull Request has been released
            Service URL: ${{ steps.deploy.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
